[package]
name = "grpc-api"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tonic = "0.5"
tokio = { version = "1", features = ["full"] }
prost = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
tonic-build = "0.5"

